// <auto-generated />
using System;
using ITG_Cafeteria.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ITG_Cafeteria.Server.Migrations
{
    [DbContext(typeof(CafeteriaDbContext))]
    [Migration("20260624112921_AddRolesAndUserManagement")]
    partial class AddRolesAndUserManagement
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ITG_Cafeteria.Server.Models.Entities.CafeteriaUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("CafeteriaUsers");
                });

            modelBuilder.Entity("ITG_Cafeteria.Server.Models.Entities.MenuDay", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("int");

                    b.Property<int>("WeeklyMenuId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("WeeklyMenuId", "DayOfWeek")
                        .IsUnique();

                    b.ToTable("MenuDays");
                });

            modelBuilder.Entity("ITG_Cafeteria.Server.Models.Entities.MenuNode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("MenuDayId")
                        .HasColumnType("int");

                    b.Property<int?>("ParentId")
                        .HasColumnType("int");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.HasIndex("MenuDayId", "ParentId", "SortOrder");

                    b.ToTable("MenuNodes");
                });

            modelBuilder.Entity("ITG_Cafeteria.Server.Models.Entities.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("ITG_Cafeteria.Server.Models.Entities.UserRole", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles");
                });

            modelBuilder.Entity("ITG_Cafeteria.Server.Models.Entities.WeeklyMenu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("PublishedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly>("WeekStartDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("WeekStartDate");

                    b.ToTable("WeeklyMenus");
                });

            modelBuilder.Entity("ITG_Cafeteria.Server.Models.Entities.MenuDay", b =>
                {
                    b.HasOne("ITG_Cafeteria.Server.Models.Entities.WeeklyMenu", "WeeklyMenu")
                        .WithMany("Days")
                        .HasForeignKey("WeeklyMenuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WeeklyMenu");
                });

            modelBuilder.Entity("ITG_Cafeteria.Server.Models.Entities.MenuNode", b =>
                {
                    b.HasOne("ITG_Cafeteria.Server.Models.Entities.MenuDay", "MenuDay")
                        .WithMany("Nodes")
                        .HasForeignKey("MenuDayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ITG_Cafeteria.Server.Models.Entities.MenuNode", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("MenuDay");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("ITG_Cafeteria.Server.Models.Entities.UserRole", b =>
                {
                    b.HasOne("ITG_Cafeteria.Server.Models.Entities.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ITG_Cafeteria.Server.Models.Entities.CafeteriaUser", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ITG_Cafeteria.Server.Models.Entities.WeeklyMenu", b =>
                {
                    b.HasOne("ITG_Cafeteria.Server.Models.Entities.CafeteriaUser", "CreatedByUser")
                        .WithMany("WeeklyMenus")
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedByUser");
                });

            modelBuilder.Entity("ITG_Cafeteria.Server.Models.Entities.CafeteriaUser", b =>
                {
                    b.Navigation("UserRoles");

                    b.Navigation("WeeklyMenus");
                });

            modelBuilder.Entity("ITG_Cafeteria.Server.Models.Entities.MenuDay", b =>
                {
                    b.Navigation("Nodes");
                });

            modelBuilder.Entity("ITG_Cafeteria.Server.Models.Entities.MenuNode", b =>
                {
                    b.Navigation("Children");
                });

            modelBuilder.Entity("ITG_Cafeteria.Server.Models.Entities.Role", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("ITG_Cafeteria.Server.Models.Entities.WeeklyMenu", b =>
                {
                    b.Navigation("Days");
                });
#pragma warning restore 612, 618
        }
    }
}
